Vagrant.configure("2") do |c|
  c.vm.box = "cloud-ubuntu1204"
  c.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
  c.vm.hostname = "default-ubuntu1204.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
